
spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: root
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#阿里云OSS
aliyun:
  oss:
    access-key-id: LTAI5tMoEF3CmVqjrR4yP5e4
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-secret: BjvK1Bn1PDc6eV9imGXfjFr3CafZ9d
    bucket-name: ssai33-tlias


#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
